language: node_js
node_js:
  - "7"
install:
  - npm install
  - npm run build
script:
  - cat ./identity/known_hosts >> ~/.ssh/known_hosts
  - chmod 600 ./identity/WebGisKey
  - scp -i ./identity/WebGisKey -r ./dist/static root@115.159.65.170:/home/nginx/web-gis
  - scp -i ./identity/WebGisKey  ./dist/index.html root@115.159.65.170:/home/nginx/web-gis

